# Generated by Django 4.0.3 on 2022-03-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='portal.author'),
        ),
    ]
