# Generated by Django 4.0.3 on 2022-06-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_category_subscribers_delete_usercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
